default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e5
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: false
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
            
HandAgent:
    num_epoch: 3
    time_horizon: 256
    batch_size: 1024
    buffer_size: 4096
    max_steps: 1e7
    summary_freq: 50000
    num_layers: 3
    hidden_units: 256
    normalize: true
    behavioral_cloning:
        demo_path: PerfectDemonstration.demo
        strength: 0.5
        steps: 50000
    reward_signals:
        gail:
            strength: 1
            gamma: 0.99
            demo_path: PerfectDemonstration.demo         
          